### ISSUE TITLE
Add surface_plot code and related

### ISSUE THREAD

**Issue by duetosymmetry** [vijayvarma392/black_hole_scattering#1]
- Make a cmdline argument to enable surface_plot
- Fix color mapping for surface_plot
- Move # of pts on backplanes into low/hi res blocks. Default to low res for real-time, hi res for saved movie OR if using surface_plot

**Comment by duetosymmetry** [comment]
cmdline argument done, haven't addressed # pts or color mapping

**Comment by vijayvarma392** [comment]
Moving to projects and closing:
https://github.com/vijayvarma392/black_hole_scattering/projects/2?add_cards_query=is%3Aopen
