### ISSUE TITLE
BBH_animation is calling unavailable model 

### ISSUE THREAD

**Issue by matijsv** [vijayvarma392/black_hole_scattering#11]
Line 766 in BBH_animation calls surfinBH.LoadFits with 'surfinBH7dq2' 

Following this fit's link as defined in surfinBH.LoadFits at line 89 leads to a non-existant zenodo page, i guess zenodo gets rid of them after a while.

I updated the links in there:
https://github.com/vijayvarma392/surfinBH/pull/21

**Comment by duetosymmetry** [comment]
Zenodo does not get rid of files; we are investigating the issue.

**Comment by duetosymmetry** [comment]
There has already been a bug filed with zenodo: https://github.com/zenodo/zenodo/issues/2487

**Comment by duetosymmetry** [comment]
Zenodo has corrected this issue.
